version: '2'

networks:
  progrid_grid_internal:
services:
  progrid:
    image: selenium/hub:3.1.0
    container_name: progrid
    privileged: true
    ports:
      - 4444:4444
    environment:
      - GRID_TIMEOUT=240000
      - GRID_BROWSER_TIMEOUT=240000
    networks:
      - progrid_grid_internal

  nodechrome:
    image: selenium/node-chrome-debug:3.1.0
    privileged: true
    depends_on:
      - progrid
    ports:
      - 5900
    environment:
      - TZ=Europe/London
      - HUB_PORT_4444_TCP_ADDR=progrid
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - progrid_grid_internal

  nodefirefox:
    image: selenium/node-firefox-debug:3.1.0
    privileged: true
    depends_on:
      - progrid
    ports:
      - 5901
    environment:
      - TZ=Europe/London
      - HUB_PORT_4444_TCP_ADDR=progrid
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - progrid_grid_internal
